### ISSUE TITLE
(Potentially) wrong year in the bibtex files

### ISSUE THREAD

**Issue by manuelhaussmann** [mlresearch/v115#1]
Great to see that UAI now also has their proceedings via PMLR. 

However, since UAI 2019 was only now added, the generated bibtex files give the year as 2020, while the month is correct. Should the bibtexfiles be backdated to 2019 since the conference was last year, or is the 2020 technically correct as the official PMLR proceedings are from 2020?

**Comment by lawrennd** [comment]
Hi Manuel, Yes, your suspicion is right. Since the proceedings only went up in 2020 (in August), the publication date is 2020.

With luck, in future, it will be easier to put proceedings up before the conference like ICML, AISTATS, COLT etc do.

**Comment by manuelhaussmann** [comment]
Alright, thanks for the quick reply.
